trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sudip100955238.azurecr.io'  # Replace with your ACR service connection
    repository: 'hello-world'  # Replace with your ACR repository name
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'd8c99020-9fe5-4df4-b702-4b7ef095a58e'  # Replace with your Azure subscription service connection
    appName: 'Neupanes'  # Replace with your Azure App Service name
    imageName: 'sudip100955238.azurecr.io/hello-world:latest'  # Replace with your ACR image path
